### ISSUE TITLE
Mandatory parameters + bic?

### ISSUE THREAD

**Issue by tiborepcek** [softwavesk/payBySquare4s#1]
Ahoj, Ján. :)

Píšeš, že:

> Mandatory parameters are amount, currency and iban, to omit optional parameter, one simply uses empty string as it's value.

Ale keď skúšam iba tie 3 povinné údaje, tak nevytvorí obrázok a vypíše toto:

```
payload - <amount>;<currency>;<vs>;<ss>;<ks>;<reference>;<paymentNote>;<iban>;<bic>
8
```

Keď však pridám aj bic, tak už obrázok vytvorí a nič nevypíše. Podľa mojich skúseností teda sú povinné 4 údaje takto:

`java -jar payBySquareApp-1.0.1.jar "31.5;EUR;;;;;;SK4281800000007000221411;SPSRSKBA" %CD%\qr_kod.png`

Chápem to správne?

Ďakujem za vysvetlenie. :)

**Comment by rusho** [comment]
Ahoj, vyzera ze tam mam bug, ak za poslednou `;` nic nie je, tak to beriem ako chybajuci element. Zatial to mozes obist bud tak ze tam teda das aj ten BIC, prip. tam das 1 medzeru tj. `"31.5;EUR;;;;;;SK4281800000007000221411; "`, s tou medzerou to nebude sice uplne koser, ale readery v bankovych appkach by to mali bez problemov spracovat (odskusane v TB, Fio a VUB)

**Comment by tiborepcek** [comment]
Tak teda radšej budem BIC uvádzať. :)

**Comment by rusho** [comment]
Opravene vo [verzii 1.0.2](https://github.com/softwavesk/payBySquare4s/releases/tag/1.0.2)

**Comment by tiborepcek** [comment]
Funguje, ďakujem. :)
