### ISSUE TITLE
Striping leading zeroes

### ISSUE THREAD

**Issue by SelfMan** [softwavesk/payBySquare4s#2]
Hi,
would it be possible to modify the EXE so it does not strip leading zeroes from values?
i.e. it strips **00**512334 to 512334. in VS, SS and KS.

Thanks! / Dakujem

**Comment by rusho** [comment]
VS, SS and KS are implemented as string and serialized including leading zeros ([this test](https://github.com/softwavesk/payBySquare4s/blob/5db79f94f67bc4911c59fd54c59d47e241cadf1c/src/test/scala/sk/softwave/paybysquare/PayModelSpec.scala#L17) explicitly checks this). 

Can you please provide more information on where the leading zeroes are being stripped?

**Comment by SelfMan** [comment]
I use a command like this example to generate the QR code I have attached:
payBySquareApp.exe "147.6;EUR;2024060001;0024;0008;;Uhrada FA za sluzby;SK8975000000000012345671;TATRSKBX" ".\QR2024060001.png"
<img width="144" alt="QR2024060001TEST" src="https://github.com/softwavesk/payBySquare4s/assets/2239036/628ec94f-6056-42d9-921d-f56e5b07fb50">

Then I scan the QR code with the Tatra Banka App, the leading zeroes in SS and KS are stripped, but so would be the ones in the VS if I used them.

(I know the account data and bank ID is incorrect, but that is not the poin, this is just  a test)

**Comment by rusho** [comment]
That is most likely due to implementation of scanner in Tatrabanka app, because if I scan the same QR code in other bank app (eg. Fio), leading zeroes are included 
![IMG_1946](https://github.com/softwavesk/payBySquare4s/assets/452688/ddd1fdfe-f6d4-42d8-a163-b6110e489ceb)

**Comment by SelfMan** [comment]
Ok, I understand.
Interesting is that other QR codes are interpreted correctly.
Never the less, this is a question for Tatra banka and the ticket can be closed.
Thanks!

**Comment by rusho** [comment]
Can you please provide example of QR code that Tatrabanka parses with leadeing zeroes? I've just tried to generate QR code at https://bsqr.co/generator/ which is a reference implementation by company that invented this format and Tatrabanka app stripped leading zeroes there as well. I also tested some QR codes from some of my received invoices (eg. phone bill) that included KS, and there again TB app stripped leading zeroes (`0008` -> `8`) while in other bank apps they were preserved. 

I can try to debug it, to see if there is a way to get TB app handling it better, but so far none of the QR codes I tried seem to work this way with TB and without some example QR where it works I'm unable to do that.

**Comment by SelfMan** [comment]
Hi, I went through the list of my invoices and payments and I was not able to find one that the TB App would parse correctly.
It looks like my memory is not as good as it used to be. The payments that had no stripped leading zeroes were made manually. (not using the QR code) Sorry for the confusion. I have to contact TB and ask WTF is going on.
